[project]
name = "far-space"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KamenskiyIlya", email = "kamenskj.ilya@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
far-space = "far_space:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
